### ISSUE TITLE
🐛 [BUG] - An error occurred while lsusb -t

### ISSUE THREAD

**Issue by Goodwu** [LanikSJ/lsusb#17]
### Description

"File name too long" when "lsusb -t"
![20231127-153338](https://github.com/LanikSJ/lsusb/assets/348005/73fa29d1-e813-45ce-b6af-a92da2a5222a)

### Reproduction steps

```bash
lsusb -t
```

### OS

Mac

**Comment by LanikSJ** [comment]
I'll try looking at this but I can't seem to figure it out just yet.
